image_net_classlist = {
    "0": "tench or Tinca tinca",
    "1": "goldfish or Carassius auratus",
    "2": "great white shark, white shark, man-eater, man-eating shark or Carcharodon caharias",
    "3": "tiger shark or Galeocerdo cuvieri",
    "4": "hammerhead or hammerhead shark",
    "5": "electric ray, crampfish, numbfish or torpedo",
    "6": "stingray",
    "7": "cock",
    "8": "hen",
    "9": "ostrich or Struthio camelus",
    "10": "brambling or Fringilla montifringilla",
    "11": "goldfinch or Carduelis carduelis",
    "12": "house finch, linnet or Carpodacus mexicanus",
    "13": "junco or snowbird",
    "14": "indigo bunting, indigo finch, indigo bird or Passerina cyanea",
    "15": "robin, American robin or Turdus migratorius",
    "16": "bulbul",
    "17": "jay",
    "18": "magpie",
    "19": "chickadee",
    "20": "water ouzel or dipper",
    "21": "kite",
    "22": "bald eagle, American eagle or Haliaeetus leucocephalus",
    "23": "vulture",
    "24": "great grey owl, great gray owl or Strix nebulosa",
    "25": "European fire salamander or Salamandra salamandra",
    "26": "common newt or Triturus vulgaris",
    "27": "eft",
    "28": "spotted salamander or Ambystoma maculatum",
    "29": "axolotl, mud puppy or Ambystoma mexicanum",
    "30": "bullfrog or Rana catesbeiana",
    "31": "tree frog, tree-frog",
    "32": "tailed frog, bell toad, ribbed toad, tailed toad or Ascaphus trui",
    "33": "loggerhead, loggerhead turtle or Caretta caretta",
    "34": "leatherback turtle, leatherback, leathery turtle or Dermochelys coriacea",
    "35": "mud turtle",
    "36": "terrapin",
    "37": "box turtle or box tortoise",
    "38": "banded gecko",
    "39": "common iguana, iguana or Iguana iguana",
    "40": "American chameleon, anole or Anolis carolinensis",
    "41": "whiptail or whiptail lizard",
    "42": "agama",
    "43": "frilled lizard or Chlamydosaurus kingi",
    "44": "alligator lizard",
    "45": "Gila monster or Heloderma suspectum",
    "46": "green lizard or Lacerta viridis",
    "47": "African chameleon or Chamaeleo chamaeleon",
    "48": "Komodo dragon, Komodo lizard, dragon lizard, giant lizard or Varanus komodoeis",
    "49": "African crocodile, Nile crocodile or Crocodylus niloticus",
    "50": "American alligator or Alligator mississipiensis",
    "51": "triceratops",
    "52": "thunder snake, worm snake or Carphophis amoenus",
    "53": "ringneck snake, ring-necked snake or ring snake",
    "54": "hognose snake, puff adder or sand viper",
    "55": "green snake or grass snake",
    "56": "king snake or kingsnake",
    "57": "garter snake or grass snake",
    "58": "water snake",
    "59": "vine snake",
    "60": "night snake or Hypsiglena torquata",
    "61": "boa constrictor or Constrictor constrictor",
    "62": "rock python, rock snake or Python sebae",
    "63": "Indian cobra or Naja naja",
    "64": "green mamba",
    "65": "sea snake",
    "66": "horned viper, cerastes, sand viper, horned asp or Cerastes cornutus",
    "67": "diamondback, diamondback rattlesnake or Crotalus adamanteus",
    "68": "sidewinder, horned rattlesnake or Crotalus cerastes",
    "69": "trilobite",
    "70": "harvestman, daddy longlegs or Phalangium opilio",
    "71": "scorpion",
    "72": "black and gold garden spider or Argiope aurantia",
    "73": "barn spider or Araneus cavaticus",
    "74": "garden spider or Aranea diademata",
    "75": "black widow or Latrodectus mactans",
    "76": "tarantula",
    "77": "wolf spider or hunting spider",
    "78": "tick",
    "79": "centipede",
    "80": "black grouse",
    "81": "ptarmigan",
    "82": "ruffed grouse, partridge or Bonasa umbellus",
    "83": "prairie chicken, prairie grouse or prairie fowl",
    "84": "peacock",
    "85": "quail",
    "86": "partridge",
    "87": "African grey, African gray or Psittacus erithacus",
    "88": "macaw",
    "89": "sulphur-crested cockatoo, Kakatoe galerita or Cacatua galerita",
    "90": "lorikeet",
    "91": "coucal",
    "92": "bee eater",
    "93": "hornbill",
    "94": "hummingbird",
    "95": "jacamar",
    "96": "toucan",
    "97": "drake",
    "98": "red-breasted merganser or Mergus serrator",
    "99": "goose",
    "100": "black swan or Cygnus atratus",
    "101": "tusker",
    "102": "echidna, spiny anteater or anteater",
    "103": "platypus, duckbill, duckbilled platypus, duck-billed platypus or Ornithorhyhus anatinus",
    "104": "wallaby or brush kangaroo",
    "105": "koala, koala bear, kangaroo bear, native bear or Phascolarctos cinereus",
    "106": "wombat",
    "107": "jellyfish",
    "108": "sea anemone or anemone",
    "109": "brain coral",
    "110": "flatworm or platyhelminth",
    "111": "nematode, nematode worm or roundworm",
    "112": "conch",
    "113": "snail",
    "114": "slug",
    "115": "sea slug or nudibranch",
    "116": "chiton, coat-of-mail shell, sea cradle or polyplacophore",
    "117": "chambered nautilus, pearly nautilus or nautilus",
    "118": "Dungeness crab or Cancer magister",
    "119": "rock crab or Cancer irroratus",
    "120": "fiddler crab",
    "121": "king crab, Alaska crab, Alaskan king crab, Alaska king crab or Paralithodesamtschatica",
    "122": "American lobster, Northern lobster, Maine lobster or Homarus americanus",
    "123": "spiny lobster, langouste, rock lobster, crawfish, crayfish or sea crawfish",
    "124": "crayfish, crawfish, crawdad or crawdaddy",
    "125": "hermit crab",
    "126": "isopod",
    "127": "white stork or Ciconia ciconia",
    "128": "black stork or Ciconia nigra",
    "129": "spoonbill",
    "130": "flamingo",
    "131": "little blue heron or Egretta caerulea",
    "132": "American egret, great white heron or Egretta albus",
    "133": "bittern",
    "134": "crane or bird",
    "135": "limpkin or Aramus pictus",
    "136": "European gallinule or Porphyrio porphyrio",
    "137": "American coot, marsh hen, mud hen, water hen or Fulica americana",
    "138": "bustard",
    "139": "ruddy turnstone or Arenaria interpres",
    "140": "red-backed sandpiper, dunlin or Erolia alpina",
    "141": "redshank or Tringa totanus",
    "142": "dowitcher",
    "143": "oystercatcher or oyster catcher",
    "144": "pelican",
    "145": "king penguin or Aptenodytes patagonica",
    "146": "albatross or mollymawk",
    "147": "grey whale, gray whale, devilfish, Eschrichtius gibbosus or Eschrichtius rostus",
    "148": "killer whale, killer, orca, grampus, sea wolf or Orcinus orca",
    "149": "dugong or Dugong dugon",
    "150": "sea lion",
    "151": "Chihuahua",
    "152": "Japanese spaniel",
    "153": "Maltese dog, Maltese terrier or Maltese",
    "154": "Pekinese, Pekingese or Peke",
    "155": "Shih-Tzu",
    "156": "Blenheim spaniel",
    "157": "papillon",
    "158": "toy terrier",
    "159": "Rhodesian ridgeback",
    "160": "Afghan hound or Afghan",
    "161": "basset or basset hound",
    "162": "beagle",
    "163": "bloodhound or sleuthhound",
    "164": "bluetick",
    "165": "black-and-tan coonhound",
    "166": "Walker hound or Walker foxhound",
    "167": "English foxhound",
    "168": "redbone",
    "169": "borzoi or Russian wolfhound",
    "170": "Irish wolfhound",
    "171": "Italian greyhound",
    "172": "whippet",
    "173": "Ibizan hound or Ibizan Podenco",
    "174": "Norwegian elkhound or elkhound",
    "175": "otterhound or otter hound",
    "176": "Saluki or gazelle hound",
    "177": "Scottish deerhound or deerhound",
    "178": "Weimaraner",
    "179": "Staffordshire bullterrier or Staffordshire bull terrier",
    "180": "American Staffordshire terrier, Staffordshire terrier, American pit bull rrier or pit bull terrier",
    "181": "Bedlington terrier",
    "182": "Border terrier",
    "183": "Kerry blue terrier",
    "184": "Irish terrier",
    "185": "Norfolk terrier",
    "186": "Norwich terrier",
    "187": "Yorkshire terrier",
    "188": "wire-haired fox terrier",
    "189": "Lakeland terrier",
    "190": "Sealyham terrier or Sealyham",
    "191": "Airedale or Airedale terrier",
    "192": "cairn or cairn terrier",
    "193": "Australian terrier",
    "194": "Dandie Dinmont or Dandie Dinmont terrier",
    "195": "Boston bull or Boston terrier",
    "196": "miniature schnauzer",
    "197": "giant schnauzer",
    "198": "standard schnauzer",
    "199": "Scotch terrier, Scottish terrier or Scottie",
    "200": "Tibetan terrier or chrysanthemum dog",
    "201": "silky terrier or Sydney silky",
    "202": "soft-coated wheaten terrier",
    "203": "West Highland white terrier",
    "204": "Lhasa or Lhasa apso",
    "205": "flat-coated retriever",
    "206": "curly-coated retriever",
    "207": "golden retriever",
    "208": "Labrador retriever",
    "209": "Chesapeake Bay retriever",
    "210": "German short-haired pointer",
    "211": "vizsla or Hungarian pointer",
    "212": "English setter",
    "213": "Irish setter or red setter",
    "214": "Gordon setter",
    "215": "Brittany spaniel",
    "216": "clumber or clumber spaniel",
    "217": "English springer or English springer spaniel",
    "218": "Welsh springer spaniel",
    "219": "cocker spaniel, English cocker spaniel or cocker",
    "220": "Sussex spaniel",
    "221": "Irish water spaniel",
    "222": "kuvasz",
    "223": "schipperke",
    "224": "groenendael",
    "225": "malinois",
    "226": "briard",
    "227": "kelpie",
    "228": "komondor",
    "229": "Old English sheepdog or bobtail",
    "230": "Shetland sheepdog, Shetland sheep dog or Shetland",
    "231": "collie",
    "232": "Border collie",
    "233": "Bouvier des Flandres or Bouviers des Flandres",
    "234": "Rottweiler",
    "235": "German shepherd, German shepherd dog, German police dog or alsatian",
    "236": "Doberman or Doberman pinscher",
    "237": "miniature pinscher",
    "238": "Greater Swiss Mountain dog",
    "239": "Bernese mountain dog",
    "240": "Appenzeller",
    "241": "EntleBucher",
    "242": "boxer",
    "243": "bull mastiff",
    "244": "Tibetan mastiff",
    "245": "French bulldog",
    "246": "Great Dane",
    "247": "Saint Bernard or St Bernard",
    "248": "Eskimo dog or husky",
    "249": "malamute, malemute or Alaskan malamute",
    "250": "Siberian husky",
    "251": "dalmatian, coach dog or carriage dog",
    "252": "affenpinscher, monkey pinscher or monkey dog",
    "253": "basenji",
    "254": "pug, pug-dog",
    "255": "Leonberg",
    "256": "Newfoundland or Newfoundland dog",
    "257": "Great Pyrenees",
    "258": "Samoyed or Samoyede",
    "259": "Pomeranian",
    "260": "chow or chow chow",
    "261": "keeshond",
    "262": "Brabancon griffon",
    "263": "Pembroke or Pembroke Welsh corgi",
    "264": "Cardigan or Cardigan Welsh corgi",
    "265": "toy poodle",
    "266": "miniature poodle",
    "267": "standard poodle",
    "268": "Mexican hairless",
    "269": "timber wolf, grey wolf, gray wolf or Canis lupus",
    "270": "white wolf, Arctic wolf or Canis lupus tundrarum",
    "271": "red wolf, maned wolf, Canis rufus or Canis niger",
    "272": "coyote, prairie wolf, brush wolf or Canis latrans",
    "273": "dingo, warrigal, warragal or Canis dingo",
    "274": "dhole or Cuon alpinus",
    "275": "African hunting dog, hyena dog, Cape hunting dog or Lycaon pictus",
    "276": "hyena or hyaena",
    "277": "red fox or Vulpes vulpes",
    "278": "kit fox or Vulpes macrotis",
    "279": "Arctic fox, white fox or Alopex lagopus",
    "280": "grey fox, gray fox or Urocyon cinereoargenteus",
    "281": "tabby or tabby cat",
    "282": "tiger cat",
    "283": "Persian cat",
    "284": "Siamese cat or Siamese",
    "285": "Egyptian cat",
    "286": "cougar, puma, catamount, mountain lion, painter, panther or Felis concolor",
    "287": "lynx or catamount",
    "288": "leopard or Panthera pardus",
    "289": "snow leopard, ounce or Panthera uncia",
    "290": "jaguar, panther, Panthera onca or Felis onca",
    "291": "lion, king of beasts or Panthera leo",
    "292": "tiger or Panthera tigris",
    "293": "cheetah, chetah or Acinonyx jubatus",
    "294": "brown bear, bruin or Ursus arctos",
    "295": "American black bear, black bear, Ursus americanus or Euarctos americanus",
    "296": "ice bear, polar bear, Ursus Maritimus or Thalarctos maritimus",
    "297": "sloth bear, Melursus ursinus or Ursus ursinus",
    "298": "mongoose",
    "299": "meerkat or mierkat",
    "300": "tiger beetle",
    "301": "ladybug, ladybeetle, lady beetle, ladybird or ladybird beetle",
    "302": "ground beetle or carabid beetle",
    "303": "long-horned beetle, longicorn or longicorn beetle",
    "304": "leaf beetle or chrysomelid",
    "305": "dung beetle",
    "306": "rhinoceros beetle",
    "307": "weevil",
    "308": "fly",
    "309": "bee",
    "310": "ant, emmet or pismire",
    "311": "grasshopper or hopper",
    "312": "cricket",
    "313": "walking stick, walkingstick or stick insect",
    "314": "cockroach or roach",
    "315": "mantis or mantid",
    "316": "cicada or cicala",
    "317": "leafhopper",
    "318": "lacewing or lacewing fly",
    "319": "dragonfly, darning needle, devil's darning needle, sewing needle, snake fder, snake doctor, mosquito hawk or skeeter hawk",
    "320": "damselfly",
    "321": "admiral",
    "322": "ringlet or ringlet butterfly",
    "323": "monarch, monarch butterfly, milkweed butterfly or Danaus plexippus",
    "324": "cabbage butterfly",
    "325": "sulphur butterfly or sulfur butterfly",
    "326": "lycaenid or lycaenid butterfly",
    "327": "starfish or sea star",
    "328": "sea urchin",
    "329": "sea cucumber or holothurian",
    "330": "wood rabbit, cottontail or cottontail rabbit",
    "331": "hare",
    "332": "Angora or Angora rabbit",
    "333": "hamster",
    "334": "porcupine or hedgehog",
    "335": "fox squirrel, eastern fox squirrel or Sciurus niger",
    "336": "marmot",
    "337": "beaver",
    "338": "guinea pig or Cavia cobaya",
    "339": "sorrel",
    "340": "zebra",
    "341": "hog, pig, grunter, squealer or Sus scrofa",
    "342": "wild boar, boar or Sus scrofa",
    "343": "warthog",
    "344": "hippopotamus, hippo, river horse or Hippopotamus amphibius",
    "345": "ox",
    "346": "water buffalo, water ox, Asiatic buffalo or Bubalus bubalis",
    "347": "bison",
    "348": "ram or tup",
    "349": "bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain eep or Ovis canadensis",
    "350": "ibex or Capra ibex",
    "351": "hartebeest",
    "352": "impala or Aepyceros melampus",
    "353": "gazelle",
    "354": "Arabian camel, dromedary or Camelus dromedarius",
    "355": "llama",
    "356": "weasel",
    "357": "mink",
    "358": "polecat, fitch, foulmart, foumart or Mustela putorius",
    "359": "black-footed ferret, ferret or Mustela nigripes",
    "360": "otter",
    "361": "skunk, polecat or wood pussy",
    "362": "badger",
    "363": "armadillo",
    "364": "three-toed sloth, ai or Bradypus tridactylus",
    "365": "orangutan, orang, orangutang or Pongo pygmaeus",
    "366": "gorilla or Gorilla gorilla",
    "367": "chimpanzee, chimp or Pan troglodytes",
    "368": "gibbon or Hylobates lar",
    "369": "siamang, Hylobates syndactylus or Symphalangus syndactylus",
    "370": "guenon or guenon monkey",
    "371": "patas, hussar monkey or Erythrocebus patas",
    "372": "baboon",
    "373": "macaque",
    "374": "langur",
    "375": "colobus or colobus monkey",
    "376": "proboscis monkey or Nasalis larvatus",
    "377": "marmoset",
    "378": "capuchin, ringtail or Cebus capucinus",
    "379": "howler monkey or howler",
    "380": "titi or titi monkey",
    "381": "spider monkey or Ateles geoffroyi",
    "382": "squirrel monkey or Saimiri sciureus",
    "383": "Madagascar cat, ring-tailed lemur or Lemur catta",
    "384": "indri, indris, Indri indri or Indri brevicaudatus",
    "385": "Indian elephant or Elephas maximus",
    "386": "African elephant or Loxodonta africana",
    "387": "lesser panda, red panda, panda, bear cat, cat bear or Ailurus fulgens",
    "388": "giant panda, panda, panda bear, coon bear or Ailuropoda melanoleuca",
    "389": "barracouta or snoek",
    "390": "eel",
    "391": "coho, cohoe, coho salmon, blue jack, silver salmon or Oncorhynchus kisutch",
    "392": "rock beauty or Holocanthus tricolor",
    "393": "anemone fish",
    "394": "sturgeon",
    "395": "gar, garfish, garpike, billfish or Lepisosteus osseus",
    "396": "lionfish",
    "397": "puffer, pufferfish, blowfish or globefish",
    "398": "abacus",
    "399": "abaya",
    "400": "academic gown, academic robe, judge's robe",
    "401": "accordion, piano accordion or squeeze box",
    "402": "acoustic guitar",
    "403": "aircraft carrier, carrier, flattop or attack aircraft carrier",
    "404": "airliner",
    "405": "airship or dirigible",
    "406": "altar",
    "407": "ambulance",
    "408": "amphibian or amphibious vehicle",
    "409": "analog clock",
    "410": "apiary or bee house",
    "411": "apron",
    "412": "ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustb, trash barrel or trash bin",
    "413": "assault rifle or assault gun",
    "414": "backpack, back pack, knapsack, packsack, rucksack or haversack",
    "415": "bakery, bakeshop or bakehouse",
    "416": "balance beam or beam",
    "417": "balloon",
    "418": "ballpoint, ballpoint pen, ballpen or Biro",
    "419": "Band Aid",
    "420": "banjo",
    "421": "bannister, banister, balustrade, balusters or handrail",
    "422": "barbell",
    "423": "barber chair",
    "424": "barbershop",
    "425": "barn",
    "426": "barometer",
    "427": "barrel or cask",
    "428": "barrow, garden cart, lawn cart or wheelbarrow",
    "429": "baseball",
    "430": "basketball",
    "431": "bassinet",
    "432": "bassoon",
    "433": "bathing cap or swimming cap",
    "434": "bath towel",
    "435": "bathtub, bathing tub, bath or tub",
    "436": "beach wagon, station wagon, wagon, estate car, beach waggon, station wagg or waggon",
    "437": "beacon, lighthouse, beacon light or pharos",
    "438": "beaker",
    "439": "bearskin, busby or shako",
    "440": "beer bottle",
    "441": "beer glass",
    "442": "bell cote or bell cot",
    "443": "bib",
    "444": "bicycle-built-for-two, tandem bicycle or tandem",
    "445": "bikini, two-piece",
    "446": "binder, ring-binder",
    "447": "binoculars, field glasses or opera glasses",
    "448": "birdhouse",
    "449": "boathouse",
    "450": "bobsled, bobsleigh or bob",
    "451": "bolo tie, bolo, bola tie or bola",
    "452": "bonnet or poke bonnet",
    "453": "bookcase",
    "454": "bookshop, bookstore or bookstall",
    "455": "bottlecap",
    "456": "bow",
    "457": "bow tie, bow-tie or bowtie",
    "458": "brass, memorial tablet or plaque",
    "459": "brassiere, bra or bandeau",
    "460": "breakwater, groin, groyne, mole, bulwark, seawall or jetty",
    "461": "breastplate, aegis or egis",
    "462": "broom",
    "463": "bucket or pail",
    "464": "buckle",
    "465": "bulletproof vest",
    "466": "bullet train or bullet",
    "467": "butcher shop or meat market",
    "468": "cab, hack, taxi or taxicab",
    "469": "caldron or cauldron",
    "470": "candle, taper or wax light",
    "471": "cannon",
    "472": "canoe",
    "473": "can opener or tin opener",
    "474": "cardigan",
    "475": "car mirror",
    "476": "carousel, carrousel, merry-go-round, roundabout or whirligig",
    "477": "carpenter's kit or tool kit",
    "478": "carton",
    "479": "car wheel",
    "480": "cash machine, cash dispenser, automated teller machine, automatic teller chine, automated teller, automatic teller or ATM",
    "481": "cassette",
    "482": "cassette player",
    "483": "castle",
    "484": "catamaran",
    "485": "CD player",
    "486": "cello or violoncello",
    "487": "cellular telephone, cellular phone, cellphone, cell or mobile phone",
    "488": "chain",
    "489": "chainlink fence",
    "490": "chain mail, ring mail, mail, chain armor, chain armour, ring armor or ring mour",
    "491": "chain saw or chainsaw",
    "492": "chest",
    "493": "chiffonier or commode",
    "494": "chime, bell or gong",
    "495": "china cabinet or china closet",
    "496": "Christmas stocking",
    "497": "church or church building",
    "498": "cinema, movie theater, movie theatre, movie house or picture palace",
    "499": "cleaver, meat cleaver or chopper",
    "500": "cliff dwelling",
    "501": "cloak",
    "502": "clog, geta, patten or sabot",
    "503": "cocktail shaker",
    "504": "coffee mug",
    "505": "coffeepot",
    "506": "coil, spiral, volute, whorl or helix",
    "507": "combination lock",
    "508": "computer keyboard or keypad",
    "509": "confectionery, confectionary or candy store",
    "510": "container ship, containership or container vessel",
    "511": "convertible",
    "512": "corkscrew or bottle screw",
    "513": "cornet, horn, trumpet or trump",
    "514": "cowboy boot",
    "515": "cowboy hat, ten-gallon hat",
    "516": "cradle",
    "517": "crane",
    "518": "crash helmet",
    "519": "crate",
    "520": "crib or cot",
    "521": "Crock Pot",
    "522": "croquet ball",
    "523": "crutch",
    "524": "cuirass",
    "525": "dam, dike or dyke",
    "526": "desk",
    "527": "desktop computer",
    "528": "dial telephone or dial phone",
    "529": "diaper, nappy or napkin",
    "530": "digital clock",
    "531": "digital watch",
    "532": "dining table or board",
    "533": "dishrag or dishcloth",
    "534": "dishwasher, dish washer or dishwashing machine",
    "535": "disk brake or disc brake",
    "536": "dock, dockage or docking facility",
    "537": "dogsled, dog sled or dog sleigh",
    "538": "dome",
    "539": "doormat or welcome mat",
    "540": "drilling platform or offshore rig",
    "541": "drum, membranophone or tympan",
    "542": "drumstick",
    "543": "dumbbell",
    "544": "Dutch oven",
    "545": "electric fan or blower",
    "546": "electric guitar",
    "547": "electric locomotive",
    "548": "entertainment center",
    "549": "envelope",
    "550": "espresso maker",
    "551": "face powder",
    "552": "feather boa or boa",
    "553": "file, file cabinet or filing cabinet",
    "554": "fireboat",
    "555": "fire engine or fire truck",
    "556": "fire screen or fireguard",
    "557": "flagpole or flagstaff",
    "558": "flute or transverse flute",
    "559": "folding chair",
    "560": "football helmet",
    "561": "forklift",
    "562": "fountain",
    "563": "fountain pen",
    "564": "four-poster",
    "565": "freight car",
    "566": "French horn or horn",
    "567": "frying pan, frypan or skillet",
    "568": "fur coat",
    "569": "garbage truck or dustcart",
    "570": "gasmask, respirator or gas helmet",
    "571": "gas pump, gasoline pump, petrol pump or island dispenser",
    "572": "goblet",
    "573": "go-kart",
    "574": "golf ball",
    "575": "golfcart or golf cart",
    "576": "gondola",
    "577": "gong, tam-tam",
    "578": "gown",
    "579": "grand piano or grand",
    "580": "greenhouse, nursery or glasshouse",
    "581": "grille or radiator grille",
    "582": "grocery store, grocery, food market or market",
    "583": "guillotine",
    "584": "hair slide",
    "585": "hair spray",
    "586": "half track",
    "587": "hammer",
    "588": "hamper",
    "589": "hand blower, blow dryer, blow drier, hair dryer or hair drier",
    "590": "hand-held computer, hand-held microcomputer",
    "591": "handkerchief, hankie, hanky or hankey",
    "592": "hard disc, hard disk or fixed disk",
    "593": "harmonica, mouth organ, harp or mouth harp",
    "594": "harp",
    "595": "harvester or reaper",
    "596": "hatchet",
    "597": "holster",
    "598": "home theater or home theatre",
    "599": "honeycomb",
    "600": "hook or claw",
    "601": "hoopskirt or crinoline",
    "602": "horizontal bar or high bar",
    "603": "horse cart, horse-cart",
    "604": "hourglass",
    "605": "iPod",
    "606": "iron or smoothing iron",
    "607": "jack-o'-lantern",
    "608": "jean, blue jean or denim",
    "609": "jeep or landrover",
    "610": "jersey, T-shirt or tee shirt",
    "611": "jigsaw puzzle",
    "612": "jinrikisha, ricksha or rickshaw",
    "613": "joystick",
    "614": "kimono",
    "615": "knee pad",
    "616": "knot",
    "617": "lab coat or laboratory coat",
    "618": "ladle",
    "619": "lampshade or lamp shade",
    "620": "laptop or laptop computer",
    "621": "lawn mower or mower",
    "622": "lens cap or lens cover",
    "623": "letter opener, paper knife or paperknife",
    "624": "library",
    "625": "lifeboat",
    "626": "lighter, light, igniter or ignitor",
    "627": "limousine or limo",
    "628": "liner or ocean liner",
    "629": "lipstick or lip rouge",
    "630": "Loafer",
    "631": "lotion",
    "632": "loudspeaker, speaker, speaker unit, loudspeaker system or speaker system",
    "633": "loupe, jeweler's loupe",
    "634": "lumbermill or sawmill",
    "635": "magnetic compass",
    "636": "mailbag or postbag",
    "637": "mailbox or letter box",
    "638": "maillot",
    "639": "maillot or tank suit",
    "640": "manhole cover",
    "641": "maraca",
    "642": "marimba or xylophone",
    "643": "mask",
    "644": "matchstick",
    "645": "maypole",
    "646": "maze or labyrinth",
    "647": "measuring cup",
    "648": "medicine chest or medicine cabinet",
    "649": "megalith or megalithic structure",
    "650": "microphone or mike",
    "651": "microwave or microwave oven",
    "652": "military uniform",
    "653": "milk can",
    "654": "minibus",
    "655": "miniskirt or mini",
    "656": "minivan",
    "657": "missile",
    "658": "mitten",
    "659": "mixing bowl",
    "660": "mobile home or manufactured home",
    "661": "Model T",
    "662": "modem",
    "663": "monastery",
    "664": "monitor",
    "665": "moped",
    "666": "mortar",
    "667": "mortarboard",
    "668": "mosque",
    "669": "mosquito net",
    "670": "motor scooter or scooter",
    "671": "mountain bike, all-terrain bike, off-roader",
    "672": "mountain tent",
    "673": "mouse or computer mouse",
    "674": "mousetrap",
    "675": "moving van",
    "676": "muzzle",
    "677": "nail",
    "678": "neck brace",
    "679": "necklace",
    "680": "nipple",
    "681": "notebook or notebook computer",
    "682": "obelisk",
    "683": "oboe, hautboy or hautbois",
    "684": "ocarina or sweet potato",
    "685": "odometer, hodometer, mileometer or milometer",
    "686": "oil filter",
    "687": "organ or pipe organ",
    "688": "oscilloscope, scope, cathode-ray oscilloscope or CRO",
    "689": "overskirt",
    "690": "oxcart",
    "691": "oxygen mask",
    "692": "packet",
    "693": "paddle or boat paddle",
    "694": "paddlewheel or paddle wheel",
    "695": "padlock",
    "696": "paintbrush",
    "697": "pajama, pyjama, pj's or jammies",
    "698": "palace",
    "699": "panpipe, pandean pipe or syrinx",
    "700": "paper towel",
    "701": "parachute or chute",
    "702": "parallel bars or bars",
    "703": "park bench",
    "704": "parking meter",
    "705": "passenger car, coach or carriage",
    "706": "patio or terrace",
    "707": "pay-phone, pay-station",
    "708": "pedestal, plinth or footstall",
    "709": "pencil box or pencil case",
    "710": "pencil sharpener",
    "711": "perfume or essence",
    "712": "Petri dish",
    "713": "photocopier",
    "714": "pick, plectrum or plectron",
    "715": "pickelhaube",
    "716": "picket fence or paling",
    "717": "pickup or pickup truck",
    "718": "pier",
    "719": "piggy bank or penny bank",
    "720": "pill bottle",
    "721": "pillow",
    "722": "ping-pong ball",
    "723": "pinwheel",
    "724": "pirate or pirate ship",
    "725": "pitcher or ewer",
    "726": "plane, carpenter's plane or woodworking plane",
    "727": "planetarium",
    "728": "plastic bag",
    "729": "plate rack",
    "730": "plow or plough",
    "731": "plunger, plumber's helper",
    "732": "Polaroid camera or Polaroid Land camera",
    "733": "pole",
    "734": "police van, police wagon, paddy wagon, patrol wagon, wagon or black Maria",
    "735": "poncho",
    "736": "pool table, billiard table or snooker table",
    "737": "pop bottle or soda bottle",
    "738": "pot or flowerpot",
    "739": "potter's wheel",
    "740": "power drill",
    "741": "prayer rug or prayer mat",
    "742": "printer",
    "743": "prison or prison house",
    "744": "projectile or missile",
    "745": "projector",
    "746": "puck or hockey puck",
    "747": "punching bag, punch bag, punching ball or punchball",
    "748": "purse",
    "749": "quill or quill pen",
    "750": "quilt, comforter, comfort or puff",
    "751": "racer, race car or racing car",
    "752": "racket or racquet",
    "753": "radiator",
    "754": "radio or wireless",
    "755": "radio telescope or radio reflector",
    "756": "rain barrel",
    "757": "recreational vehicle, RV, R.V.",
    "758": "reel",
    "759": "reflex camera",
    "760": "refrigerator or icebox",
    "761": "remote control or remote",
    "762": "restaurant, eating house, eating place or eatery",
    "763": "revolver, six-gun, six-shooter",
    "764": "rifle",
    "765": "rocking chair or rocker",
    "766": "rotisserie",
    "767": "rubber eraser, rubber or pencil eraser",
    "768": "rugby ball",
    "769": "rule or ruler",
    "770": "running shoe",
    "771": "safe",
    "772": "safety pin",
    "773": "saltshaker or salt shaker",
    "774": "sandal",
    "775": "sarong",
    "776": "sax or saxophone",
    "777": "scabbard",
    "778": "scale or weighing machine",
    "779": "school bus",
    "780": "schooner",
    "781": "scoreboard",
    "782": "screen or CRT screen",
    "783": "screw",
    "784": "screwdriver",
    "785": "seat belt or seatbelt",
    "786": "sewing machine",
    "787": "shield or buckler",
    "788": "shoe shop, shoe-shop or shoe store",
    "789": "shoji",
    "790": "shopping basket",
    "791": "shopping cart",
    "792": "shovel",
    "793": "shower cap",
    "794": "shower curtain",
    "795": "ski",
    "796": "ski mask",
    "797": "sleeping bag",
    "798": "slide rule or slipstick",
    "799": "sliding door",
    "800": "slot, one-armed bandit",
    "801": "snorkel",
    "802": "snowmobile",
    "803": "snowplow or snowplough",
    "804": "soap dispenser",
    "805": "soccer ball",
    "806": "sock",
    "807": "solar dish, solar collector or solar furnace",
    "808": "sombrero",
    "809": "soup bowl",
    "810": "space bar",
    "811": "space heater",
    "812": "space shuttle",
    "813": "spatula",
    "814": "speedboat",
    "815": "spider web, spider's web",
    "816": "spindle",
    "817": "sports car or sport car",
    "818": "spotlight or spot",
    "819": "stage",
    "820": "steam locomotive",
    "821": "steel arch bridge",
    "822": "steel drum",
    "823": "stethoscope",
    "824": "stole",
    "825": "stone wall",
    "826": "stopwatch or stop watch",
    "827": "stove",
    "828": "strainer",
    "829": "streetcar, tram, tramcar, trolley or trolley car",
    "830": "stretcher",
    "831": "studio couch or day bed",
    "832": "stupa or tope",
    "833": "submarine, pigboat, sub, U-boat",
    "834": "suit or suit of clothes",
    "835": "sundial",
    "836": "sunglass",
    "837": "sunglasses, dark glasses or shades",
    "838": "sunscreen, sunblock or sun blocker",
    "839": "suspension bridge",
    "840": "swab, swob or mop",
    "841": "sweatshirt",
    "842": "swimming trunks or bathing trunks",
    "843": "swing",
    "844": "switch, electric switch or electrical switch",
    "845": "syringe",
    "846": "table lamp",
    "847": "tank, army tank, armored combat vehicle or armoured combat vehicle",
    "848": "tape player",
    "849": "teapot",
    "850": "teddy or teddy bear",
    "851": "television or television system",
    "852": "tennis ball",
    "853": "thatch or thatched roof",
    "854": "theater curtain or theatre curtain",
    "855": "thimble",
    "856": "thresher, thrasher or threshing machine",
    "857": "throne",
    "858": "tile roof",
    "859": "toaster",
    "860": "tobacco shop, tobacconist shop or tobacconist",
    "861": "toilet seat",
    "862": "torch",
    "863": "totem pole",
    "864": "tow truck, tow car or wrecker",
    "865": "toyshop",
    "866": "tractor",
    "867": "trailer truck, tractor trailer, trucking rig, rig, articulated lorry or sem",
    "868": "tray",
    "869": "trench coat",
    "870": "tricycle, trike or velocipede",
    "871": "trimaran",
    "872": "tripod",
    "873": "triumphal arch",
    "874": "trolleybus, trolley coach or trackless trolley",
    "875": "trombone",
    "876": "tub or vat",
    "877": "turnstile",
    "878": "typewriter keyboard",
    "879": "umbrella",
    "880": "unicycle or monocycle",
    "881": "upright or upright piano",
    "882": "vacuum or vacuum cleaner",
    "883": "vase",
    "884": "vault",
    "885": "velvet",
    "886": "vending machine",
    "887": "vestment",
    "888": "viaduct",
    "889": "violin or fiddle",
    "890": "volleyball",
    "891": "waffle iron",
    "892": "wall clock",
    "893": "wallet, billfold, notecase or pocketbook",
    "894": "wardrobe, closet or press",
    "895": "warplane or military plane",
    "896": "washbasin, handbasin, washbowl, lavabo, wash-hand basin",
    "897": "washer, automatic washer or washing machine",
    "898": "water bottle",
    "899": "water jug",
    "900": "water tower",
    "901": "whiskey jug",
    "902": "whistle",
    "903": "wig",
    "904": "window screen",
    "905": "window shade",
    "906": "Windsor tie",
    "907": "wine bottle",
    "908": "wing",
    "909": "wok",
    "910": "wooden spoon",
    "911": "wool, woolen or woollen",
    "912": "worm fence, snake fence, snake-rail fence or Virginia fence",
    "913": "wreck",
    "914": "yawl",
    "915": "yurt",
    "916": "web site, website, internet site or site",
    "917": "comic book",
    "918": "crossword puzzle or crossword",
    "919": "street sign",
    "920": "traffic light, traffic signal or stoplight",
    "921": "book jacket, dust cover, dust jacket or dust wrapper",
    "922": "menu",
    "923": "plate",
    "924": "guacamole",
    "925": "consomme",
    "926": "hot pot or hotpot",
    "927": "trifle",
    "928": "ice cream or icecream",
    "929": "ice lolly, lolly, lollipop or popsicle",
    "930": "French loaf",
    "931": "bagel or beigel",
    "932": "pretzel",
    "933": "cheeseburger",
    "934": "hotdog, hot dog or red hot",
    "935": "mashed potato",
    "936": "head cabbage",
    "937": "broccoli",
    "938": "cauliflower",
    "939": "zucchini or courgette",
    "940": "spaghetti squash",
    "941": "acorn squash",
    "942": "butternut squash",
    "943": "cucumber or cuke",
    "944": "artichoke or globe artichoke",
    "945": "bell pepper",
    "946": "cardoon",
    "947": "mushroom",
    "948": "Granny Smith",
    "949": "strawberry",
    "950": "orange",
    "951": "lemon",
    "952": "fig",
    "953": "pineapple or ananas",
    "954": "banana",
    "955": "jackfruit, jak or jack",
    "956": "custard apple",
    "957": "pomegranate",
    "958": "hay",
    "959": "carbonara",
    "960": "chocolate sauce or chocolate syrup",
    "961": "dough",
    "962": "meat loaf or meatloaf",
    "963": "pizza or pizza pie",
    "964": "potpie",
    "965": "burrito",
    "966": "red wine",
    "967": "espresso",
    "968": "cup",
    "969": "eggnog",
    "970": "alp",
    "971": "bubble",
    "972": "cliff, drop, drop-off",
    "973": "coral reef",
    "974": "geyser",
    "975": "lakeside or lakeshore",
    "976": "promontory, headland, head or foreland",
    "977": "sandbar or sand bar",
    "978": "seashore, coast, seacoast, sea-coast",
    "979": "valley or vale",
    "980": "volcano",
    "981": "ballplayer or baseball player",
    "982": "groom or bridegroom",
    "983": "scuba diver",
    "984": "rapeseed",
    "985": "daisy",
    "986": "yellow lady's slipper, yellow lady-slipper, Cypripedium calceolus or Cypripium parviflorum",
    "987": "corn",
    "988": "acorn",
    "989": "hip, rose hip or rosehip",
    "990": "buckeye, horse chestnut or conker",
    "991": "coral fungus",
    "992": "agaric",
    "993": "gyromitra",
    "994": "stinkhorn or carrion fungus",
    "995": "earthstar",
    "996": "hen-of-the-woods, hen of the woods, Polyporus frondosus or Grifola frondosa",
    "997": "bolete",
    "998": "ear, spike or capitulum",
    "999": "toilet tissue, toilet paper or bathroom tissue",
}
